version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: dctd-mysql-server
    restart: always
    environment:
      MYSQL_DATABASE: db-games
      MYSQL_ROOT_PASSWORD: dctd01
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initrd.d/init.sql
    networks:
      - app-network
volumes:
  db:
    driver: local

networks:
  app-network:
    driver: bridge